### ISSUE TITLE
Runtime Error: expected Variable or None (got torch.FloatTensor)

### ISSUE THREAD

**Issue by yazar1993** [meijieru/crnn.pytorch#133]
Getting this error when running cost.backward()
How could I fix this?

**Comment by meijieru** [comment]
Version of pytorch?

**Comment by yazar1993** [comment]
0.3.0

**Comment by meijieru** [comment]
Could not reproduce.
You should provide as much information as possible, otherwise nobody could help you.

**Comment by yazar1993** [comment]
What other information would you like?
I'm using Ubuntu 16.04, CUDA 9. Done the installation using a conda environment. 
Would it be possible for you to upload your conda environment as a yaml file for me to use?

**Comment by meijieru** [comment]
At least the backtrace should be provided.

**Comment by yazar1993** [comment]
![image](https://user-images.githubusercontent.com/13361158/40834209-e391e92c-6598-11e8-8b52-b58b0e58176d.png)

This is the traceback. Any clue why this could be happening?

**Comment by yazar1993** [comment]
Solved:
warp-ctc commit from 9 days ago made the problem:
![image](https://user-images.githubusercontent.com/13361158/40834908-c47efed8-659a-11e8-8d25-8b521218852e.png)

Checkout to that version and then it is solved.

**Comment by meijieru** [comment]
That change requires PyTorch 0.4.

**Comment by Aurora11111** [comment]
@meijieru @yazar1993 I have checked that my pytorch veriosn is 0.4.0,and modified the __init__.py in warp_ctc,still the same issue occurs.

**Comment by meijieru** [comment]
@DLUTfangping @Aurora11111 You should use warp-ctc's previous commit for PyTorch 0.3

**Comment by Aurora11111** [comment]
@meijieru I have tried pytorch 4.0 is ok

**Comment by ZhuLingfeng1993** [comment]
I have modified the init.py in warp_ctc,still the same issue occurs.

**Comment by Aurora11111** [comment]
@ZhuLingfeng1993 you should not modified the init.py following above,you should modified as below:
Line 4 :add-->  from torch.autograd import Variable
Line  46:
              delete-->#ctx.grads = grads
             add--> ctx.grads = Variable(grads,volatile=True)

**Comment by ZhuLingfeng1993** [comment]
Thank you so much.I have solved the problem.

**Comment by ZhuLingfeng1993** [comment]
After  I run the steup.py in warp-ctc/pytorch_binding again,the problem was solved.
